In [2]:
from xmen import evaluation
from xmen.data import make_document, Entity, Concept

In [3]:
gt = [make_document([
    Entity([[0, 5]], "entity", concepts=[]),
    Entity([[6, 10]], "entity", concepts=[]),
    Entity([[11, 15]], "entity", concepts=[]),
    Entity([[30, 35]], "entity", concepts=[]),
    Entity([[40, 45]], "entity", concepts=[])
])]
pred = [make_document([
    Entity([[0, 7]], "entity", concepts=[]),  # be
    Entity([[8, 13]], "entity", concepts=[]),  # be
    Entity([[36, 40]], "entity", concepts=[]),  # fp
    Entity([[45, 50]], "entity", concepts=[])  # fp
])]
ea_df = evaluation.error_analysis(gt, pred)

In [4]:
ea_df

,_word_len,_abbrev,gt_start,gt_end,gt_text,pred_start,pred_end,pred_text,ner_match_type,gold_concept,gold_type,pred_index,pred_index_score,pred_top,pred_top_score,corpus_id,document_id
0,1.0,False,0.0,5.0,[entity],0.0,7.0,[entity],be,{'db_id': 'NIL'},None,0,None,NIL,None,x,1
1,1.0,False,6.0,10.0,[entity],0.0,7.0,[entity],be,{'db_id': 'NIL'},None,0,None,NIL,None,x,1
2,1.0,False,6.0,10.0,[entity],8.0,13.0,[entity],be,{'db_id': 'NIL'},None,0,None,NIL,None,x,1
3,1.0,False,11.0,15.0,[entity],8.0,13.0,[entity],be,{'db_id': 'NIL'},None,0,None,NIL,None,x,1
4,1.0,False,30.0,35.0,[entity],NaN,NaN,None,fn,{'db_id': 'NIL'},None,0,None,NIL,None,x,1
5,NaN,None,NaN,NaN,None,36.0,40.0,[entity],fp,None,None,-1,None,None,None,x,1
6,1.0,False,40.0,45.0,[entity],NaN,NaN,None,fn,{'db_id': 'NIL'},None,0,None,NIL,None,x,1
7,NaN,None,NaN,NaN,None,45.0,50.0,[entity],fp,None,None,-1,None,None,None,x,1